### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by cored** [thoughtbot/weechat-slacklog#14]
I download the script putting on `~/.weechat/ruby/slacklog.rb` but when trying to load it with 
`script load slacklog.rb` I get the following error:

```
:17:50” =!= | ruby: error while loading file "/home/homer/.weechat/ruby/slacklog.rb"
                    │“10:17:50” =!= | ruby: error: eval:31:in `module_eval': uninitialized constant Encoding::UTF_7 (NameError)
                    │“10:17:50” =!= | ruby: error:      from /usr/lib/ruby/2.2.0/uri/common.rb:15:in `<top (required)>'
                    │“10:17:50” =!= | ruby: error:      from /usr/lib/ruby/2.2.0/uri.rb:104:in `require'
                    │“10:17:50” =!= | ruby: error:      from /usr/lib/ruby/2.2.0/uri.rb:104:in `<top (required)>'
                    │“10:17:50” =!= | ruby: error:      from /usr/lib/ruby/2.2.0/net/http.rb:23:in `require'
                    │“10:17:50” =!= | ruby: error:      from /usr/lib/ruby/2.2.0/net/http.rb:23:in `<top (required)>'
                    │“10:17:50” =!= | ruby: error:      from /usr/lib/ruby/2.2.0/net/https.rb:21:in `require'                                                                  
                    │“10:17:50” =!= | ruby: error:      from /usr/lib/ruby/2.2.0/net/https.rb:21:in `<top (required)>'                                       
                    │“10:17:50” =!= | ruby: error:      from (eval):32:in `require'           
                    │“10:17:50” =!= | ruby: error:      from (eval):32:in `load_eval_file'                                   
                    │“10:17:50” =!= | ruby: error:      from eval:31:in `module_eval'
                    │“10:17:50” =!= | ruby: error:      from eval:31:in `load_eval_file'
```

Weechat version 1.2

**Comment by jferris** [comment]
This is a bug in Weechat: https://github.com/weechat/weechat/issues/433
